# .github/workflows/gh-pages.yml

name: GitHub Pages

on:
  push:
    branches:
      - master

env:
  GOOGLE_API: ${{ secrets.GOOGLE_API }}

jobs:
  build-deploy:
    runs-on: ubuntu-24.04
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true
          fetch-depth: 0

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "latest"
      
      - name: Inject Google Maps API Key
        run: |
          find ./layouts/partials -type f -name "reviews-map.html" -exec sed -i "s|__GOOGLE_API__|${GOOGLE_API}|g" {} +

      - name: Build
        run: hugo --minify

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/master' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./public
